// Content for cards that link to their own detail page (services, team, paint
// types) — kept separate from Home.jsx so the grid views (Home.jsx) and the
// detail-page routes (ServiceDetail.jsx / TeamDetail.jsx / PaintDetail.jsx)
// share one source of truth instead of duplicating copy.

export const SERVICES = [
  { slug: 'interior-painting', bg: 'linear-gradient(135deg,#0d2137,#1c4068,#f2871f)', icon: 'home', accent: '#f2871f', title: 'Interior Painting',
    bullets: ['Premium emulsion, distemper & luxury finishes', 'Full furniture protection — zero mess guaranteed'],
    detail: [
      'A full interior repaint starts with covering every piece of furniture and the floor before a single tin is opened. We fill cracks, sand uneven patches, and apply primer before the finish coats go on — so the final colour goes down smooth and even, not over old imperfections.',
      'Which paint we recommend depends on the room and how it\'s actually used, not a one-size-fits-all default. Budget-conscious spaces like store rooms or a rental property usually make sense with distemper or Tractor Emulsion — both water-based, fast-drying, and easy to touch up. Living rooms and main bedrooms are where most homeowners step up to Asian Paints Royale or Royale Shyne: richer colour depth, better washability, and a finish that still looks good years later. Doors, window frames, and grills are a separate decision entirely — those need an oil-based enamel (see our Paint Types guide for why walls and woodwork use fundamentally different paint chemistry).',
      'Every interior job includes wall levelling with putty where needed, two coats minimum for even colour, and a final walkthrough before we consider it done — see our How It Works page for the full step-by-step process.',
    ] },
  { slug: 'exterior-painting', bg: 'linear-gradient(135deg,#081627,#163457,#2563c4)', icon: 'construction', accent: '#2563c4', title: 'Exterior Painting',
    bullets: ['Weather-resistant & UV-protective coatings', 'Surface prep, crack filling & primer included'],
    detail: [
      'Exterior walls take a real beating from Delhi NCR\'s sun, monsoon, and pollution — so we use weatherproof, UV-resistant exterior emulsions like Asian Paints Apex, formulated to resist algae and fungal growth in humid conditions rather than a standard interior emulsion that isn\'t built for outdoor exposure.',
      'Every job starts with a proper survey of the facade for cracks, dampness, and old flaking paint, then crack-filling, a coat of exterior primer, and two finish coats — not just a fresh colour painted directly over existing problems. Skipping prep is the single biggest reason exterior paint jobs fail early: a coat applied over a hairline crack or damp patch will bubble or peel within one monsoon regardless of how good the paint itself is.',
      'If the facade also has visible seepage or a history of damp patches appearing indoors, that\'s usually a separate underlying issue — see our Waterproofing service, since painting over an active leak point just delays the problem rather than fixing it.',
    ] },
  { slug: 'waterproofing', bg: 'linear-gradient(135deg,#072a2b,#0d4547,#0ea5a8)', icon: 'water', accent: '#0ea5a8', title: 'Waterproofing',
    bullets: ['Surface waterproof coatings for seepage, dampness & wall leakages', 'Crack sealing with quality waterproofing paint solutions'],
    detail: [
      'Seepage almost always starts as an exterior problem — a hairline crack, a terrace losing its protective coating, a gap around a window frame — that shows up as a damp patch somewhere else entirely, often a room or a floor away from the actual entry point. Water travels through the smallest opening and follows gravity, not a straight line, which is why guessing at the source from where the stain appears indoors is usually wrong.',
      'We inspect the likely entry points first — terrace surfaces, external wall cracks, and window/door frame joints — and treat them with crack-filling and a quality waterproof coating rather than just repainting over the visible damp patch, which is why painting alone over a seepage-affected wall usually resurfaces within one monsoon cycle. This is surface-level waterproofing treatment, not large-scale structural work (basement tanking, full membrane systems, or plumbing repairs) — for a major structural leak, we\'ll say so upfront rather than take on something outside what we do.',
      'Once the source is treated and fully dried, we repaint the affected area to match — so the fix is both practical and cosmetic, not one without the other.',
    ] },
  { slug: 'royale-emulsion', bg: 'linear-gradient(135deg,#1a0f2e,#3b1f5c,#7c3aed)', icon: 'crown', accent: '#7c3aed', title: 'Royale Emulsion',
    bullets: ['Smooth, washable, lasting premium finish', 'Asian Paints Royale — stays vibrant for years'],
    detail: [
      'Asian Paints Royale is our go-to premium finish for living rooms and feature walls — a smooth, non-reflective luxury emulsion that hides minor wall imperfections and tolerates a damp-cloth wipe. It\'s a water-based acrylic emulsion, meaning it dries faster than an oil-based paint, has far less odour during application, and won\'t yellow over time the way an oil-based finish can.',
      'For an even higher-sheen, more washable finish, Royale Shyne Luxury Emulsion is the step up — Teflon surface protection, an anti-bacterial and anti-fungal shield, and an 8-year performance warranty, at a noticeably higher sheen than standard Royale. Both are designed for interior walls specifically; neither is the right choice for doors, window frames, or metal grills, which need an oil-based enamel instead. See our full Paint Types guide for the complete comparison, including where oil-based paint is actually the better choice.',
    ] },
  { slug: 'texture-designer', bg: 'linear-gradient(135deg,#2a0f1e,#5c1f3f,#db2777)', icon: 'brush', accent: '#db2777', title: 'Texture & Designer',
    bullets: ['Unique 3D textures and designer wall finishes', 'Custom patterns for a premium luxury look'],
    detail: [
      'Decorative textured finishes turn a single wall into a statement — stone-effect, fabric-effect, and abstract 3D patterns applied by hand for a designer look that flat paint can\'t give you. These are typically applied with trowels, rollers, and stencils in multiple layers, so the timeline runs longer than a standard flat-colour wall — usually two to three days for one feature wall depending on the complexity of the pattern.',
      'Popular for living-room feature walls, entryways, and TV units where you want one wall to stand out rather than repainting the whole room in a bold colour. We show physical sample boards on-site before starting, since texture patterns photograph very differently from how they look and feel in person under real room lighting.',
    ] },
  { slug: 'putty-primer', bg: 'linear-gradient(135deg,#0f172a,#334155,#475569)', icon: 'layers', accent: '#475569', title: 'Putty & Primer',
    bullets: ['Crack filling and professional wall levelling', 'Perfect surface prep for a flawless paint job'],
    detail: [
      'The step most repaints skip — and the one that determines whether the final coat looks flawless or shows every bump underneath. We fill cracks, level uneven patches with wall putty (usually white cement-based putty for interiors), sand it smooth, and apply the right primer for the surface and paint type before any finish coat goes on.',
      'It adds roughly a day to the timeline for an average room, and it\'s the difference between an average repaint and one that actually looks premium — paint (however good the brand) only ever looks as smooth as the surface underneath it. Skipping primer specifically also means the finish coat absorbs unevenly into bare or previously-distempered walls, leading to patchy colour that needs an extra coat to fix anyway — so it rarely actually saves time in practice.',
    ] },
];

export const TEAM = [
  { slug: 'rajeev-kumar', name: 'Rajeev Kumar', role: 'Director — Delivery & Operations', img: null, initials: 'RK', color: '#163457',
    bio: 'With 10+ years leading painting and quality work, Rajeev heads customer relationships and operations. A passionate artist whose craftsmanship has made lasting impressions across Delhi NCR.' },
  { slug: 'sonia-gupta', name: 'Sonia Gupta', role: 'Marketing & Digital Growth', img: '/images/sonia.webp', initials: 'SG', color: '#2563c4',
    bio: 'With 20+ years of experience leading teams and managing large projects, Sonia drives The Painter Boys\' digital transformation. Former consultant for Fortune 500 companies, she has handled both international and national clients, and now helps homeowners achieve their dream spaces.' },
  { slug: 'susheel-rai', name: 'Dr. Susheel Rai', role: 'Head of Operations', img: '/images/susheel.jpg', initials: 'SR', color: '#0ea5a8',
    bio: 'Overseeing operations with decades of leadership experience. His philosophy — caring for people and putting their needs first — defines The Painter Boys\' service culture throughout.' },
];

// oilOrWater: 'Water-based' | 'Oil-based' — every paint on this site is one
// or the other; see PAINT_BASE_GUIDE below for what that distinction means
// and why it drives which paint goes where (walls vs. doors/metal).
export const PAINT_TYPES = [
  { slug: 'asian-paints-royale', name: 'Asian Paints Royale', tier: 'Luxury', finish: 'Smooth matt luxury emulsion',
    oilOrWater: 'Water-based', coverage: '~140-150 sq ft/litre (2 coats)', bestFor: 'Living rooms, bedrooms, feature walls',
    desc: 'A premium interior emulsion known for its rich, smooth, non-reflective finish that hides minor wall imperfections and tolerates a damp-cloth wipe. Being water-based, it dries within a few hours per coat, has minimal odour during application, and won\'t yellow with age the way an oil-based paint can. Popular for living rooms and feature walls where a luxury look matters, and it\'s the finish most homeowners upgrade to from a standard distemper repaint.',
    longRead: [
      { heading: 'What Makes Royale Different From an Ordinary Emulsion',
        paragraphs: [
          'Most people\'s first question when we recommend Asian Paints Royale over a cheaper emulsion is simple: what are they actually paying extra for? The honest answer is in the resin. Royale uses a higher grade of acrylic binder than economy and mid-range emulsions, which is the part of the paint that holds the pigment particles onto the wall once the water carrier evaporates. A better binder means the pigment is packed more densely and more evenly across the surface, which is why Royale reads as a deeper, richer colour than the same shade painted in a budget emulsion — you\'re not just paying for the tin, you\'re paying for colour that actually looks like the shade card under real room lighting, not a washed-out approximation of it.',
          'That same binder quality is also what gives Royale its smooth, low-sheen "matt" finish rather than a flat, chalky one. A flat finish scatters light unevenly and shows roller marks and touch-up patches under any angled light — a hallway spotlight, morning sun through a window — because the surface is microscopically rough. Royale\'s finish is engineered to be smoother at that microscopic level, so it reflects light more consistently across the whole wall. That\'s the difference customers are usually pointing at when they say a Royale wall "looks more expensive" without being able to explain exactly why.',
        ] },
      { heading: 'Health & Indoor Air Quality Benefits',
        paragraphs: [
          'Royale is a water-based acrylic emulsion, which matters for anyone actually living in the space while — and immediately after — it\'s painted. Water-based paints carry their pigment and resin in water rather than a petroleum solvent, so there\'s no strong solvent smell filling the house for days, no need to keep windows open around the clock, and a much lower load of Volatile Organic Compounds (VOCs) off-gassing into the air your family breathes. That\'s a real, practical difference from an oil-based enamel, which relies on a chemical thinner as its carrier and can leave a lingering smell — and a genuine VOC load — for a noticeably longer stretch after application.',
          'This is especially relevant for bedrooms, children\'s rooms, and any home with someone who has respiratory sensitivity, asthma, or is simply trying to avoid strong chemical smells during a repaint. With Royale, most households can sleep in a freshly painted room the same night or the next, once it\'s touch-dry, rather than needing to air out the house for several days the way an oil-based repaint often requires. It also means less residual odour clinging to curtains, soft furnishings, and clothing stored in the room — a common but underrated complaint with solvent-heavy paints.',
          'Royale also dries to a finish that\'s genuinely washable with a damp cloth and mild soap, which sounds like a convenience feature but has a hygiene angle too — spills, fingerprints near light switches, and everyday marks near door frames can actually be wiped off rather than left to accumulate, or worse, scrubbed hard enough to strip the paint. For homes with young children or pets, that washability turns into fewer touch-up repaints and a wall surface that stays cleaner between full repaints, rather than trapping dust and grime the way a flat distemper finish tends to.',
        ] },
      { heading: 'Where Royale Actually Earns Its Price', paragraphs: [
        'We steer Royale toward the rooms where people spend real time and where guests actually see the finish up close — living rooms, main bedrooms, dining areas, and any single feature wall meant to make a statement. It\'s less necessary in store rooms, utility areas, or rarely-used guest rooms, where a Tractor Emulsion repaint does the job for meaningfully less cost with very little visible difference to daily life. Knowing where to spend the Royale budget and where not to is genuinely part of what a good painting contractor should be advising on, not just applying whatever\'s ordered.',
        'One thing worth knowing before committing to Royale: its finish shows underlying wall texture more clearly than a flatter, cheaper emulsion does, precisely because of that smoother, denser resin film. That means proper putty levelling beforehand isn\'t optional if you want the "expensive" look — see our Putty & Primer service — because Royale will faithfully show off a poorly prepared wall just as much as it shows off a well-prepped one. The paint itself isn\'t what makes a Royale job look premium; the paint plus a properly levelled surface underneath it is.',
      ] },
      { heading: 'Coats, Coverage, and Getting a Longer-Lasting Job', paragraphs: [
        'Two coats over a primed, putty-levelled wall is the standard for Royale, and skipping to a single coat to save time or paint almost always shows — colour depth and evenness noticeably suffer, and the wall ages patchier because thin spots wear through faster. Coverage runs roughly 140-150 sq ft per litre per coat on a reasonably smooth wall, though a heavily textured or previously dark-coloured wall will pull that number down since more paint gets absorbed into the surface or is needed to fully mask the old colour.',
        'A properly done Royale wall, kept clean with occasional damp-cloth wiping rather than scrubbing, typically holds its colour and finish well for 4-5 years before it starts to look like it needs a refresh — longer in low-traffic rooms, shorter in kitchens, hallways, or anywhere it takes more daily contact. That lifespan, combined with the washability that keeps it looking fresh in between, is the real return on the higher upfront cost compared to a budget emulsion that needs repainting sooner just to stay presentable.',
      ] },
      { heading: 'Royale vs. Royale Shyne: Which One Actually Fits Your Room', paragraphs: [
        'The two get confused often enough that it\'s worth a direct answer: standard Royale is a smooth matt finish, Royale Shyne is the higher-sheen step up with added Teflon protection and an anti-microbial shield. Royale is the safer, more forgiving choice for most rooms — its matt finish hides minor wall imperfections rather than highlighting them, and it works well across a whole home\'s worth of bedrooms and living spaces without demanding perfect wall prep everywhere. Royale Shyne is the more deliberate, statement-piece choice best reserved for a single feature wall or a formal room that\'s had proper putty levelling done specifically to support that higher-sheen look — see the Royale Shyne guide for the full comparison.',
      ] },
    ] },
  { slug: 'tractor-emulsion', name: 'Tractor Emulsion', tier: 'Economy', finish: 'Matt emulsion',
    oilOrWater: 'Water-based', coverage: '~120-130 sq ft/litre (2 coats)', bestFor: 'Bedrooms, budget interior repaints',
    desc: 'Asian Paints\' value-for-money emulsion range — a practical, washable, water-based finish for bedrooms and interiors where budget matters without giving up a clean matt look. It doesn\'t have the depth of colour or the washability of Royale, but for a straightforward repaint of a less-used room, it\'s a genuinely sensible choice rather than a compromise — most of the visible difference between Tractor and Royale only shows up in high-traffic, high-visibility spaces.',
    longRead: [
      { heading: 'Why Tractor Emulsion Exists, and Who It’s Actually For', paragraphs: [
        `Tractor Emulsion is Asian Paints' answer to a question every homeowner eventually asks: does every room in the house really need premium paint? For most homes the honest answer is no. A store room, a rarely-used guest bedroom, a rental property between tenants, or a first coat for someone repainting on a tight budget after a big move — these are exactly the situations Tractor was engineered for. It's a straightforward water-based matt emulsion built to do one job well: give a wall a clean, even, washable finish at a price that makes repainting an entire home affordable rather than a stretch.`,
        `We're often asked whether "economy" paint means a compromise on quality that will show up later as flaking, patchiness, or a short lifespan. It doesn't work that way. Tractor is still a genuine acrylic emulsion from an established paint chemistry, not a diluted or inferior formulation — the difference from Royale isn't that it's a worse product, it's that it's a simpler one, with less of the specialty resin and fewer of the finish-enhancing additives that push Royale's price up. For a wall that isn't being scrutinised up close under living-room lighting every day, that simpler formulation does the job completely adequately.`,
      ] },
      { heading: 'Health and Safety Benefits of a Water-Based Economy Paint', paragraphs: [
        `Because Tractor is water-based rather than solvent-based, it shares the same core health advantage every emulsion in our range does over an oil-based enamel: low odour, low VOC off-gassing, and a fast return to normal room use after painting. This matters just as much — arguably more — in budget repaint scenarios, where the whole point is often to get a space usable again quickly, whether that's a rental turnaround between tenants or a room a family needs back in daily use within a day or two.`,
        `Because Tractor dries quickly with minimal fumes, it's a genuinely practical choice for spaces used by children, elderly family members, or anyone sensitive to strong paint smells — you're not trading health and comfort for the lower price, since that trade-off doesn't really exist between different water-based emulsions in the first place. The washable matt finish also means everyday marks and light grime can be wiped rather than left to build up, which keeps a budget-painted room from looking tired faster than it needs to.`,
      ] },
      { heading: 'Where the Difference From Royale Actually Shows', paragraphs: [
        `Being direct about the trade-offs is more useful than pretending there aren't any. Tractor's colour depth is noticeably flatter than Royale's under close inspection or strong directional light — the pigment density simply isn't the same. It's also less washable over the long run; it'll tolerate a gentle wipe for everyday marks, but repeated scrubbing wears the finish faster than Royale's tougher film would. And coverage runs slightly lower per litre — roughly 120-130 sq ft compared to Royale's 140-150 — because the binder-to-pigment ratio is different.`,
        `None of that matters much in a store room, a rarely-photographed guest room, or a rental unit where the next tenant will likely want their own colour anyway. It matters a lot in a living room or main bedroom where the finish is on daily display — which is exactly why we don't recommend Tractor across an entire home indiscriminately, and instead suggest reserving the Royale budget for the two or three rooms that actually get seen and lived in, while Tractor handles the rest just as reliably for meaningfully less cost.`,
      ] },
      { heading: 'Getting the Most Out of a Tractor Repaint', paragraphs: [
        `Surface prep matters just as much with an economy emulsion as with a premium one — arguably more, since Tractor has less of a forgiving, self-levelling film to mask an uneven wall underneath it. Skipping putty and primer to save further cost on a Tractor job is usually a false economy: the paint goes down patchy over an unprepared surface regardless of price tier, and the room ends up needing a repaint sooner than it should have. Two coats over a properly primed wall remains the standard even at this price point.`,
        `Kept clean and touched up promptly when marks appear, a Tractor-painted room typically holds up well for 3-4 years before it needs a fresh coat — shorter than Royale's 4-5, but entirely reasonable for a space that isn't taking heavy daily wear. For anyone repainting a full house on a budget, our usual advice is simple: Tractor for the rooms people pass through, Royale for the rooms people live in.`,
      ] },
      { heading: 'Common Questions About Tractor Emulsion', paragraphs: [
        `Will Tractor look "cheap" compared to Royale? Not in a room that isn't under close daily scrutiny — most people can't reliably tell the two apart from across a room, only up close under strong light. The visible gap shows up mainly in colour depth on bold or dark shades and in how the wall holds up to repeated wiping, not in a quick glance.`,
        `Can Tractor be used on ceilings as well as walls? Yes — it's a common, sensible choice for ceilings throughout a home even when walls get Royale, since ceilings rarely get touched or scrutinised up close the way a wall at eye level does, making it one of the easiest places to save on the overall repaint budget without any visible trade-off.`,
        `Is it worth upgrading a Tractor-painted room to Royale later? Generally yes, if the room's use changes — a store room converted into a home office or guest room, for instance. Because Tractor is a genuine acrylic emulsion and not a fundamentally different chemistry, a Royale repaint over an existing Tractor wall in good condition is a straightforward job, not a strip-and-restart situation.`,
      ] },
    ] },
  { slug: 'royale-shyne-luxury-emulsion', name: 'Royale Shyne Luxury Emulsion', tier: 'Luxury', finish: 'High-sheen luxury emulsion',
    oilOrWater: 'Water-based', coverage: '~100-120 sq ft/litre (2 coats)', bestFor: 'Statement walls, high-traffic living spaces',
    desc: 'Asian Paints\' top-tier luxury emulsion — one step above standard Royale, with a high-sheen, reflective finish, Teflon surface protection, an anti-bacterial and anti-fungal shield, and an 8-year performance warranty. Still water-based like Royale (fast-drying, low odour), but formulated for noticeably superior stain resistance and washability. The higher sheen shows off wall imperfections more than a matt finish does, so it works best on walls that have already had proper putty levelling — see our Putty & Primer service.',
    longRead: [
      { heading: 'What Sets Royale Shyne Apart From Standard Royale', paragraphs: [
        `Royale Shyne sits at the very top of Asian Paints' interior emulsion range, and the name is a fair description of what you actually get: a noticeably higher sheen than standard Royale, closer to a soft satin glow than a flat matt. That extra reflectivity comes from a denser, more refined acrylic resin film than even standard Royale uses — the same underlying chemistry family, pushed further. The practical result is a wall that looks genuinely luminous under both daylight and warm evening lighting, which is exactly why it's become the default choice for statement walls, formal living rooms, and any space meant to make an impression the moment someone walks in.`,
        `Teflon surface protection is the other headline feature, and it's a real functional benefit, not just marketing language. The Teflon-based additive creates a surface that actively resists dust and stains from settling into the paint film, which means the wall stays looking clean for noticeably longer between wipe-downs than an untreated emulsion would. Combined with an anti-bacterial and anti-fungal shield built into the formulation, Royale Shyne is engineered to actively resist the two things that make painted walls look tired over time in Indian conditions — accumulated grime and the fungal growth that humid seasons and monsoon dampness can encourage on interior walls.`,
      ] },
      { heading: 'Health Benefits: Why an Anti-Bacterial, Anti-Fungal Wall Finish Matters', paragraphs: [
        `The anti-bacterial and anti-fungal properties of Royale Shyne aren't just a durability feature — they have a genuine indoor health angle that's worth understanding properly. Painted walls, especially in humid climates or rooms with limited ventilation (bathrooms adjacent to bedrooms, north-facing rooms that don't get much sun, homes near the monsoon-prone parts of Delhi NCR), can develop microscopic mould and bacterial growth within the paint film over time, particularly if the wall was ever damp. This isn't always visible early on — it often shows up first as a faint musty smell or subtle discolouration long before an obvious mould patch appears.`,
        `A wall finished in Royale Shyne actively resists that growth at the surface level, which matters directly for anyone in the household with allergies, asthma, or general respiratory sensitivity — airborne mould spores from wall surfaces are a recognised trigger for both. For a child's bedroom, an elderly family member's room, or simply a home in a humidity-prone location, that anti-microbial shield is a meaningful, ongoing health benefit rather than a one-time cosmetic upgrade, quietly working in the background for as long as the paint film stays intact.`,
        `Like every emulsion in our range, Royale Shyne is also water-based, so the same low-VOC, low-odour benefits apply here too: minimal fumes during application, a fast return to normal use of the room, and none of the lingering solvent smell that comes with an oil-based alternative. You get the deepest, glossiest finish in the emulsion range without any of the health trade-offs typically associated with achieving a high-gloss look through an oil-based enamel instead.`,
      ] },
      { heading: 'The 8-Year Warranty and What It Actually Reflects', paragraphs: [
        `Asian Paints backs Royale Shyne with an 8-year performance warranty, which is the longest in the interior emulsion range and reflects genuine confidence in how the formulation holds up — not just a marketing number. In practice, that warranty period lines up with what we see on the ground: a properly applied Royale Shyne wall, on a correctly prepped surface, keeps its sheen, colour depth, and stain resistance for close to a decade before it genuinely needs a full repaint, versus the 4-5 years typical of standard Royale and considerably less for budget emulsions.`,
        `That longevity is where the higher upfront cost gets earned back — fewer repaint cycles over the life of the home, less disruption, and a wall that keeps looking premium rather than gradually dulling the way lower-tier finishes do. For a feature wall or formal living space that a family expects to enjoy for years without redecorating, Royale Shyne's cost-per-year of good looks is often more competitive than it first appears next to the sticker price of the tin.`,
      ] },
      { heading: 'Why Wall Prep Matters More With Royale Shyne Than Any Other Finish', paragraphs: [
        `Here's the trade-off nobody should gloss over: the same higher sheen that makes Royale Shyne look luxurious also makes it the least forgiving finish in our range when it comes to an imperfect wall underneath. A gloss or satin surface reflects light directly, which means every dent, uneven patch, or poorly sanded putty line becomes visible in a way it simply wouldn't on a flat, matt distemper wall. We've seen customers request Royale Shyne, skip proper putty levelling to save a day on the timeline, and end up disappointed with a wall that shows every imperfection under evening lamp light — not because the paint failed, but because the prep underneath it wasn't done to the standard the finish demands.`,
        `Our standard process for a Royale Shyne job is non-negotiable on this point: full crack-filling, putty levelling, sanding to a smooth finish, and a proper primer coat before Royale Shyne ever goes on — see our Putty & Primer service for what that involves. Done properly, the result is genuinely the best-looking wall finish we offer. Done as a shortcut over an unprepped surface, it's the finish most likely to look like a missed opportunity rather than the upgrade it's meant to be.`,
      ] },
      { heading: 'Coverage, Application, and Where to Use It', paragraphs: [
        `Royale Shyne covers roughly 100-120 sq ft per litre per coat — somewhat less than standard Royale, since the denser resin film that gives it that sheen also means slightly less spread per litre. Two coats over a fully prepped, primed wall is standard, applied with a fine-nap roller for the smoothest possible result, since the higher sheen will show roller texture more than a matt finish would if the application is rushed or uneven.`,
        `We recommend it specifically for feature walls, formal living and dining rooms, and any high-visibility space where guests spend time — the rooms where the extra cost and extra prep effort translate directly into an impression people notice. For utility spaces, store rooms, or anywhere the wall won't get close scrutiny, that budget is better spent on standard Royale or Tractor Emulsion instead, saving Royale Shyne for where its particular strengths — sheen, stain resistance, and the anti-microbial shield — actually get seen and used.`,
      ] },
    ] },
  { slug: 'apex-exterior-emulsion', name: 'Apex Exterior Emulsion', tier: 'Premium', finish: 'Weatherproof exterior',
    oilOrWater: 'Water-based', coverage: '~110-130 sq ft/litre (2 coats)', bestFor: 'Building facades, outer walls, boundary walls',
    desc: 'Built for exteriors — weather and UV resistant, formulated to resist algae/fungal growth and monsoon dampness on outer walls and building facades. It\'s a water-based acrylic exterior emulsion, not the same product as an interior emulsion with "exterior" on the label; the binder and additives are specifically engineered to flex with temperature swings and shed water rather than absorb it, which is what keeps a facade from blistering after its first proper monsoon.',
    longRead: [
      { heading: 'Why an Interior Emulsion Can’t Just Be Used Outside', paragraphs: [
        `A common misconception is that "exterior" on a paint label is mostly a marketing distinction — that any decent emulsion will do outdoors if the colour looks right. It isn't, and the difference matters within the first year of a facade's life. Interior emulsion is formulated for a stable environment: consistent room temperature, no direct sun, no rain. A building's outer wall faces the opposite of all three — direct UV exposure that breaks down ordinary pigment and binder over time, temperature swings between a hot Delhi NCR afternoon and a cool night that make the wall itself expand and contract, and monsoon rain that needs to be shed rather than absorbed.`,
        `Apex Exterior Emulsion's acrylic binder is specifically engineered to stay flexible through those temperature swings rather than becoming brittle, which is the main reason exterior walls painted with the wrong product develop hairline cracks and eventually peel within a season or two — the paint film simply can't move with the wall the way it needs to. That flexibility, combined with a water-repellent surface rather than a water-absorbent one, is the core engineering difference that justifies treating exterior paint as its own category rather than an afterthought.`,
      ] },
      { heading: 'UV Resistance and Why Facades Fade Unevenly', paragraphs: [
        `Direct sunlight breaks down paint pigment through UV radiation over time — this is why an exterior wall exposed to full sun for years fades and chalks while a wall in permanent shade on the same building still looks close to its original colour. Apex is formulated with UV-stable pigments and additives specifically to slow that fading process, keeping a facade's colour looking closer to its original shade for years longer than a standard emulsion would manage outdoors, where fading and chalking can become noticeable within a single year of harsh sun exposure.`,
        `This matters more in North India than many homeowners initially expect, given how intense and prolonged summer sun exposure is here compared to the shorter, milder seasons the paint industry's general marketing sometimes assumes. A facade that gets full afternoon sun on the west-facing side of a building is doing meaningfully harder work than the north-facing side, and that's often visible years later as a genuine colour mismatch between the two sides if a non-UV-stable paint was used — one more reason Apex earns its premium positioning on real Delhi NCR buildings rather than in a lab test somewhere cooler.`,
      ] },
      { heading: 'Algae, Fungal Growth, and Monsoon Dampness', paragraphs: [
        `Humidity is the other half of what an exterior paint has to survive here, and it's arguably the more damaging one over time. Damp exterior walls, especially on shaded or poorly ventilated sides of a building, are exactly the environment algae and fungal growth need to establish themselves — showing up first as faint green or black staining, then spreading if left untreated. Apex is formulated with anti-algal and anti-fungal additives specifically to resist that growth, which is a meaningful durability feature in a climate where the monsoon isn't a brief event but a sustained multi-month period of high humidity.`,
        `Beyond the cosmetic staining, sustained dampness in an exterior wall is also the most common root cause of interior seepage complaints — a facade that isn't shedding water properly lets moisture work its way through the wall over time and shows up as a damp patch on an interior wall, sometimes a room or floor away from where the actual problem is. A properly applied Apex exterior coat, over correctly crack-filled and primed masonry, is a genuine first line of defence against that kind of seepage — see our Waterproofing service for cases where the dampness has already progressed past what a paint coat alone can resolve.`,
      ] },
      { heading: 'What Proper Exterior Prep and Application Actually Involves', paragraphs: [
        `An exterior job starts with a full facade survey for cracks, old flaking paint, and any existing damp patches — painting directly over these problems without addressing them first is the single biggest reason exterior jobs fail early, regardless of how good the paint itself is. That means crack-filling with appropriate exterior-grade filler, removing any loose or flaking old paint back to a sound surface, and a coat of exterior primer before Apex goes on, not a shortcut straight to the finish coat.`,
        `Two finish coats is standard, covering roughly 110-130 sq ft per litre per coat on an average masonry surface, with coverage dropping on rougher or more porous walls that absorb more paint into the surface. Done properly, an Apex exterior job holds its colour, resists staining, and keeps the facade genuinely weatherproof for around 5-7 years before it needs a full repaint — considerably longer than a facade painted with an interior-grade emulsion mistakenly used outdoors, which can start visibly failing within a single monsoon cycle.`,
      ] },
      { heading: 'Timing an Exterior Job Right', paragraphs: [
        `Weather windows matter more for an exterior job than almost any other consideration. We avoid starting exterior painting during or right before monsoon season — a coat that hasn't fully cured before heavy rain hits can fail to bond properly, undermining the whole job regardless of how good the paint is. The ideal window in Delhi NCR is generally post-monsoon through the cooler months, when there's enough dry, settled weather for each coat to cure fully between applications without the risk of an unexpected downpour mid-job.`,
        `It's also worth timing an exterior repaint around any other facade work — if a building is due for waterproofing on the terrace or a crack repair on an external wall, doing that work before the Apex coat goes on means the paint isn't applied over a problem that will resurface and undermine it within a season. Sequencing the work correctly the first time is considerably cheaper than repainting the same facade twice within a couple of years.`,
      ] },
    ] },
  { slug: 'distemper', name: 'Distemper', tier: 'Budget', finish: 'Matt, basic',
    oilOrWater: 'Water-based', coverage: '~90-110 sq ft/litre (2 coats)', bestFor: 'Store rooms, rental properties, quick refreshes',
    desc: 'The most economical wall finish, suited for spaces needing a quick, affordable refresh — commonly used in budget-conscious interior projects, rental properties, or store rooms that don\'t need a premium finish. It\'s water-based and dries quickly, but it\'s also the least washable and least durable option on this list — expect to repaint sooner than with an emulsion, which is the trade-off for the lower upfront cost.',
    longRead: [
      { heading: 'What Distemper Actually Is, and Why It Still Has a Place', paragraphs: [
        `Distemper is the oldest and simplest wall-paint category still in common use, and understanding why it's so much cheaper than an emulsion comes down to what's not in the tin: distemper uses a much simpler, chalk- and water-based binder system rather than the acrylic resin that gives an emulsion like Tractor or Royale its washability and depth. That simpler formulation is exactly what keeps the cost down, and for the right space, it's a completely reasonable choice rather than a lesser one.`,
        `We recommend distemper specifically for spaces where the wall's job is simply to look clean and fresh, not to withstand years of daily wear — store rooms, quick refreshes before a property sale or rental listing, temporary structures, or interiors being repainted purely to remove old marks and staleness rather than as a long-term finish. For a homeowner repainting an entire house on a strict budget, distemper on the lowest-priority rooms frees up meaningfully more of the budget for emulsion where it actually matters.`,
      ] },
      { heading: 'Health and Application Benefits', paragraphs: [
        `Distemper shares the core health advantage every water-based finish in our range has over an oil-based enamel: very low odour, minimal VOC off-gassing, and a fast return to normal room use — often within hours rather than days. It's genuinely one of the fastest-drying wall finishes available, which is part of why it's the standard choice for a quick pre-sale or pre-rental refresh where turnaround time matters as much as the finish itself.`,
        `Because it's water-based and low-fume, distemper is safe to apply in occupied homes without needing to vacate the space, which matters for landlords repainting a unit between tenants on a tight schedule, or homeowners who need a room usable again the same day. The trade-off for that speed and low cost is durability — distemper doesn't hold up to scrubbing or heavy handling the way an emulsion does, so it's not the right choice for anywhere that gets a lot of physical contact.`,
      ] },
      { heading: 'Where Distemper Falls Short of an Emulsion — and Why That’s Fine for the Right Room', paragraphs: [
        `Being upfront about the limitations: distemper is the least washable finish we offer, marks and stains tend to soak in rather than wipe off, and the colour itself is flatter and less rich than any emulsion. It also wears faster — a distemper-painted room generally needs a repaint within 1-2 years in normal use, considerably sooner than Tractor's 3-4 years or Royale's 4-5. For a living room or bedroom in daily use, those limitations add up to a finish that looks tired faster than the modest upfront saving is usually worth.`,
        `But for a store room, a rarely-entered space, or a property being repainted purely to look presentable for a sale or rental listing where the next occupant will likely repaint anyway, none of those limitations matter in practice. Matching the finish to how the room is actually used — rather than defaulting to the cheapest option everywhere or the premium option everywhere — is the advice we give most often, and distemper is exactly the right tool for a specific, well-understood set of situations.`,
      ] },
      { heading: 'Distemper vs. Tractor Emulsion: How to Actually Choose', paragraphs: [
        `The two most common budget questions we get are "why not just use distemper everywhere" and "why not just use Tractor everywhere instead of distemper" — and the honest answer sits in the middle. Distemper is cheaper again than Tractor, but the durability gap between the two is real: Tractor's acrylic binder gives it meaningfully better washability and roughly double the useful lifespan before a repaint is needed. For anywhere with even occasional daily use — a spare bedroom, a home office, a passage — that gap in lifespan usually makes Tractor the better value over a 3-4 year horizon, even accounting for its higher upfront cost per litre.`,
        `Distemper earns its place specifically where the repaint is genuinely short-horizon by design — a property being sold or handed over to a new tenant within a year or two, a temporary space, or a room getting painted purely to remove old marks before some other renovation work happens in it anyway. If there's any real chance the room will still be in the same use three or more years from now, we'll usually recommend spending the small difference on Tractor instead, since the cost-per-year works out lower despite the higher sticker price.`,
      ] },
      { heading: 'What a Distemper Job Involves', paragraphs: [
        `Even at this price point, proper prep isn't skipped — loose or flaking old paint gets removed, cracks filled, and the surface given a basic primer coat before distemper goes on, since an unprepared wall will show through and peel prematurely regardless of which finish sits on top of it. Two coats is standard, and distemper's fast drying time (often under an hour between coats in good weather) is one of its most practical advantages when a room needs to be back in use quickly.`,
        `Coverage runs roughly 90-110 sq ft per litre per coat, generally the lowest of any product in our range, since the simpler binder system doesn't spread quite as efficiently as an acrylic emulsion's does. For a budget-conscious full-house repaint, we typically work out a room-by-room plan — distemper for the lowest-priority spaces, Tractor for everyday rooms, and Royale reserved for the one or two spaces that matter most — rather than applying one finish uniformly regardless of how each room actually gets used. If budget is the only constraint and there's no urgency around timeline, we'll always say so plainly rather than defaulting to the cheapest option out of habit — a slightly higher spend on Tractor across the whole home often works out better value over a few years than the lowest possible price today.`,
      ] },
    ] },
  { slug: 'texture-designer-finishes', name: 'Texture & Designer Finishes', tier: 'Luxury', finish: '3D texture / designer',
    oilOrWater: 'Water-based', coverage: 'Varies by pattern — quoted on-site', bestFor: 'Feature walls, entryways, TV units',
    desc: 'Decorative textured finishes for feature walls — stone, fabric and abstract patterns that add a designer touch to living rooms and entryways. These are water-based acrylic texture compounds applied in multiple layers by hand with trowels and tools rather than rolled on like a standard emulsion, which is why coverage and timeline are quoted per project instead of a flat sq ft/litre figure.',
    longRead: [
      { heading: 'What Texture Finishes Are, and How They Differ From Flat Paint', paragraphs: [
        `Texture finishes aren't really "paint" in the way an emulsion is — they're thicker, aggregate-loaded acrylic compounds designed to be shaped, not just rolled on flat. Depending on the tools and technique used, the same base compound can be worked into a rough stone-like surface, a soft fabric-effect weave, or a bold abstract pattern with visible peaks and troughs. That physical dimensionality is what separates a texture wall from even the richest flat emulsion colour — it catches light and shadow differently as the viewing angle changes through the day, which is exactly the effect that makes a single feature wall stand out in a room otherwise painted in flat colour.`,
        `Because the compound is applied by hand in multiple layers using trowels, sponges, combs, and stencils rather than rolled on in a single even pass, no two texture walls come out identical — even the same pattern applied by the same painter has natural, hand-crafted variation, which is part of the appeal rather than a flaw. It's a genuinely different skill from standard wall painting, closer to a craft than a production process, which is also why it's priced and timed per project rather than off a standard sq ft/litre rate.`,
      ] },
      { heading: 'Health and Material Safety', paragraphs: [
        `Texture compounds in our range are water-based acrylic products, sharing the same low-odour, low-VOC profile as our standard emulsions — there's no strong chemical smell during the multi-day application process, and no need to vacate the room while it's being worked on. That matters more here than with a standard repaint, since a proper texture job on a single wall typically takes two to three days of layered application and drying time, and a low-fume product makes that a non-issue for the rest of the household living around the work.`,
        `Once fully cured, a texture finish is stable and inert — it doesn't off-gas or require special ongoing ventilation the way a fresh oil-based enamel would. The main practical consideration is dust: because the surface is deliberately uneven, it can trap slightly more household dust in its crevices than a flat wall would, so a texture wall in a bedroom used by someone with dust allergies is worth discussing with us in advance — usually not a reason to avoid it, but worth factoring into where in the home it goes.`,
      ] },
      { heading: 'Where Texture Walls Work Best', paragraphs: [
        `A texture finish is a statement, not a default, and it works best applied to one wall rather than an entire room — a living room feature wall behind the sofa or TV unit, an entryway wall that makes an impression the moment someone enters, or a focal wall in a formal dining area. Applied across every wall in a room, the effect competes with itself and can start to feel overwhelming rather than striking; applied to one wall against a flat, complementary emulsion on the rest, it reads as intentional design rather than decoration for its own sake.`,
        `We always show physical sample boards on-site before starting a texture job, and this isn't a formality — texture patterns photograph very differently from how they actually look and feel under real room lighting, and a pattern that looks striking in a portfolio photo can read completely differently under warm evening lamp light in an actual living room. Seeing and touching a real sample under the room's own lighting is the only reliable way to choose a pattern you'll still like a year later.`,
      ] },
      { heading: 'Process, Timeline, and Longevity', paragraphs: [
        `A typical texture wall job runs two to three days depending on pattern complexity — base coat and levelling on day one, the textured layer applied and shaped while workable, then a protective top coat once fully cured. This is meaningfully longer than a standard emulsion wall, which is one reason it's usually reserved for a single feature wall rather than a whole room. Surface prep matters just as much here as with any other finish — an uneven wall underneath still needs putty levelling first, since the base needs to be structurally sound even though the final surface is deliberately irregular.`,
        `Well applied and properly top-coated, a texture finish is genuinely durable — the acrylic compound is tougher and thicker than standard emulsion, so it resists chipping and holds its pattern well for years, typically outlasting a standard emulsion repaint cycle on the same wall. It's not something that gets touched up easily if damaged, though — a texture wall is more of a one-time investment than an emulsion wall that gets refreshed every few years, which is worth knowing before committing to a particularly bold or unusual pattern.`,
      ] },
      { heading: 'Popular Patterns and Choosing the Right One for a Room', paragraphs: [
        `Stone-effect textures tend to suit entryways and study or home-office walls, reading as grounded and architectural rather than decorative. Fabric-effect finishes — a soft, woven-looking texture — work especially well in bedrooms and formal living rooms, where a subtler dimensional effect fits the mood better than something bold. Abstract 3D patterns with pronounced peaks and troughs are the boldest option and tend to work best on a single accent wall in a living room or behind a TV unit, where the goal is a genuine focal point rather than a background texture.`,
        `Lighting placement matters more for texture walls than for any flat-paint choice, since the whole visual effect depends on shadow being cast across the raised surface. A texture wall lit only by flat overhead lighting can look considerably less striking than the same wall with a side-angled lamp or an accent light grazing across it — something worth planning for at the same time as choosing the pattern itself, not as an afterthought once the wall is already finished.`,
      ] },
    ] },
  { slug: 'apcolite-premium-enamel', name: 'Apcolite Premium Enamel', tier: 'Premium', finish: 'High-gloss oil-based enamel',
    oilOrWater: 'Oil-based', coverage: '~95-110 sq ft/litre (2 coats)', bestFor: 'Doors, windows, grills, gates, metal railings',
    desc: 'The paint every wall emulsion on this page is not built to replace: Apcolite Premium Enamel is oil-based, formulated for wood and metal rather than plaster walls. It cures into a hard, mirror-like glossy film that\'s significantly tougher and more stain-resistant than any water-based option — the right choice for doors, window frames, grills, gates, and railings, where surfaces get handled, knocked, and exposed to weather directly. The trade-off is a longer dry time between coats, a stronger odour during application (needs ventilation), and cleanup with thinner rather than water. Available in 1700+ shades across 1L, 4L, 10L and 20L packs.',
    longRead: [
      { heading: 'Why Doors and Grills Need a Completely Different Paint From Walls', paragraphs: [
        `Every other product on this page is a water-based emulsion built for plaster walls that just sit there, absorbing nothing but ambient humidity. Doors, window frames, grills, and gates live a completely different life — they get gripped, knocked, slammed, rained on directly, and in the case of metal, exposed to the kind of temperature swings that make surfaces expand and contract noticeably more than a wall does. An emulsion applied to a door wouldn't survive normal use for more than a few months before showing wear at the handle, the hinges, and the edges. Apcolite Premium Enamel exists specifically because wood and metal need a fundamentally tougher film than any wall paint provides.`,
        `That toughness comes from being oil-based rather than water-based — the resin system cures into a hard, dense, mirror-like film through a genuinely different chemical process than an emulsion's water-evaporation drying. The result is a surface that resists scratches, knocks, and stains far better than any acrylic emulsion could, which is exactly the durability profile a door handled dozens of times a day, or a gate exposed to monsoon rain and summer sun directly, actually needs.`,
      ] },
      { heading: 'Understanding the Health and Safety Trade-Off', paragraphs: [
        `Being straightforward about this matters: Apcolite is genuinely different from the rest of our range on the health and odour front, and it's worth understanding why before committing to it for an interior application. As an oil-based enamel, it uses a solvent carrier rather than water, which means a noticeably stronger smell during application and while curing, a real (though standard-for-the-category) VOC load released as it dries, and a need for proper ventilation in the room while it's being applied and for a period afterward.`,
        `This is precisely why we only recommend Apcolite for what it's actually built for — doors, window frames, grills, gates, and metal railings — rather than as a general interior wall paint, where a water-based emulsion is both the better-performing and the healthier choice. For homes with young children, anyone with respiratory sensitivity, or simply a preference for minimal fumes indoors, keeping Apcolite confined to doors and metalwork (with good ventilation during application, and a proper airing-out period before the room returns to normal use) is the sensible way to get its durability benefits without unnecessary exposure elsewhere in the home.`,
        `Once fully cured — which takes longer than a water-based paint, typically several days to reach full hardness even though it's touch-dry sooner — Apcolite is a stable, inert, hard-wearing surface with no ongoing odour or off-gassing concern. The trade-off is genuinely front-loaded into the application period, not a lasting one.`,
      ] },
      { heading: 'Where Apcolite Belongs — and Where It Doesn’t', paragraphs: [
        `Doors and door frames, window frames, metal grills and window guards, gates, and railings are where Apcolite consistently earns its place — surfaces that get handled directly, take physical knocks, and in the case of exterior metalwork, face weather exposure that would degrade a water-based finish far faster. It's also a common choice for wooden furniture pieces built into a space, like a fitted wardrobe front, where a hard, glossy, wipeable surface matters more than it does on a plaster wall.`,
        `It's not a substitute for Royale, Royale Shyne, Tractor, or Apex on actual walls, even though all of these products sit under the same "premium paint" umbrella in a shade card. Using an oil-based enamel on interior walls is both more expensive per litre for no functional benefit on that surface, and unnecessarily brings the ventilation and odour considerations into rooms where a water-based emulsion would perform just as well or better. Matching the paint chemistry to the surface, not just the finish look, is the core judgement call we make on every job.`,
      ] },
      { heading: 'Application, Coverage, and What "1700+ Shades" Actually Means Day to Day', paragraphs: [
        `Apcolite typically needs two coats over a properly primed surface, with a noticeably longer dry time between coats than any water-based option in our range — often 8-24 hours depending on humidity and ventilation, compared to a few hours for an emulsion. That longer cure time is part of what gives the finish its hardness, so rushing a second coat before the first is properly cured is one of the more common mistakes that leads to a soft, easily-marked final finish rather than the mirror-hard one Apcolite is capable of. Coverage runs roughly 95-110 sq ft per litre per coat, and cleanup requires thinner rather than water — worth knowing before starting, since brushes and rollers can't just be rinsed at a sink the way they can with any emulsion.`,
        `The 1700+ shade range matters more practically than it might sound — it means a gate, a set of window grills, and a set of interior doors can all be colour-matched precisely to a home's palette rather than settling for whatever handful of "standard" enamel colours a smaller range would offer, which is often the difference between metalwork that looks deliberately coordinated with the rest of the house and metalwork that looks like an afterthought painted in whatever was available.`,
      ] },
      { heading: 'Maintaining an Apcolite Finish Over Time', paragraphs: [
        `A well-applied Apcolite finish on a door or gate typically holds its gloss and colour for 3-5 years indoors, somewhat less on exterior metalwork exposed to direct sun and rain, where UV exposure gradually dulls the sheen faster than it would indoors. Regular dusting and an occasional wipe with a mild soap solution keeps the surface looking its best; harsh abrasive cleaners aren't necessary and can dull the gloss prematurely, since the enamel's own hardness already handles everyday grime well without aggressive scrubbing.`,
        `Touch-ups are more visible on a glossy enamel surface than on a matt wall finish, since even a slight sheen mismatch between old and new paint catches the light differently — for a door or gate showing wear only in specific spots, a full re-coat of the affected panel usually looks better than a small patch touch-up. When it is time for a full repaint, a light sanding to key the old glossy surface is a necessary prep step, since fresh enamel won't bond well to an untouched high-gloss film underneath it.`,
      ] },
    ] },
];

// Referenced from the Paint Types listing page — the general distinction
// customers most often ask about, independent of any specific product above.
export const PAINT_BASE_GUIDE = {
  water: {
    title: 'Water-Based Paints (Emulsions)',
    points: [
      'Carrier is water, not a chemical solvent — low odour, low VOC, and cleans up with soap and water.',
      'Dries faster (typically 1-4 hours between coats), so interior jobs move quicker.',
      'Stays flexible as walls expand/contract with temperature, resisting cracking better over time.',
      'Doesn\'t yellow with age the way oil-based paint can, especially on white/light shades.',
      'Used for: interior wall emulsions, exterior wall emulsions, distemper, primers, texture finishes.',
    ],
  },
  oil: {
    title: 'Oil-Based Paints (Enamels)',
    points: [
      'Carrier is a solvent (thinner/turpentine) — stronger odour during application, needs good ventilation.',
      'Cures into a noticeably harder, glossier, more stain- and scratch-resistant film.',
      'Slower to dry (often 8-24 hours between coats) and cleans up with thinner, not water.',
      'Can yellow slightly over years, especially in low light or on pure white shades.',
      'Used for: doors, window frames, grills, gates, metal railings — surfaces that get handled or need a hard, glossy protective coat.',
    ],
  },
};
